# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NTSOMZ_BBPCatalog
                                 A QGIS plugin
 Access to BBP of RKS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-10
        copyright            : (C) 2020 by Pankin A.V. @ NTSOMZ
        email                : pankin_av@ntsomz.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NTSOMZ_BBPCatalog class from file NTSOMZ_BBPCatalog.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ntsomzBBP import NTSOMZ_BBPCatalog
    return NTSOMZ_BBPCatalog(iface)
